spring:
  application:
    name: setting

  datasource:
    url: jdbc:mysql://${LOCAL_MYSQL_HOST}:${LOCAL_MYSQL_PORT}/${LOCAL_DB_NAME}?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${LOCAL_MYSQL_USERNAME}
    password: ${LOCAL_MYSQL_PASSWORD}

  jpa:
    show-sql: true

    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect

    hibernate:
      ddl-auto: update

oauth:
  twitter:
    client-id: ${X_CLIENT_ID}
    client-secret: ${X_CLIENT_SECRET}
    challenge: ${X_CODE_CHALLENGE}

openai:
  model: gpt-4o-mini
  api-key: ${OPENAI_API_KEY}
  api-url: https://api.openai.com/v1/chat/completions